In [1]:
import numpy as np

## DataTypes and Attributes


In [2]:
# Numpy main datatype is ndarray
al=np.array([1,2,3])

In [3]:
al

array([1, 2, 3])

In [4]:
type(al)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3.3],[6,2.4,4.5]])

a3=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [7]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [9]:
a3.shape

(4, 3)

In [10]:
al

array([1, 2, 3])

In [11]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
al.ndim , a2.ndim , a3.ndim

(1, 2, 2)

In [13]:
al.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
al.size,a2.size,a3.size

(3, 6, 12)

In [15]:
type(al),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [17]:
# Create a datafram from numpy arrays

import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  6.0  2.4  4.5

## Creating Arrays

In [18]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones=np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[0, 0, 3, 3, 5],
       [9, 0, 8, 6, 1],
       [6, 0, 7, 6, 6]], dtype=int32)

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.14852561, 0.95676126, 0.97366134],
       [0.85205487, 0.16889052, 0.80845008],
       [0.73153417, 0.22638136, 0.63349328],
       [0.91648142, 0.74676473, 0.766419  ],
       [0.99499063, 0.25050644, 0.56186623]])

In [30]:
random_array_2.size

15

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.3655152 , 0.82425429, 0.52402218],
       [0.1917178 , 0.18424878, 0.38896246],
       [0.26822485, 0.80596945, 0.44154423],
       [0.62652898, 0.37974244, 0.70302162],
       [0.62412129, 0.684723  , 0.51941051]])

In [33]:
#pseudo random numbers
np.random.seed(seed=99)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[1, 3, 9],
       [8, 9, 8],
       [2, 4, 5],
       [4, 1, 7],
       [3, 7, 1]], dtype=int32)

In [34]:
random_array_4.shape

(5, 3)

In [35]:
np.random.seed(7)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [36]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [37]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 7, 8, 9], dtype=int32)

In [38]:
al


array([1, 2, 3])

In [39]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [40]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
al[0]

np.int64(1)

In [43]:
a2.shape

(2, 3)

In [42]:
a2[0]

array([1. , 2. , 3.3])

In [44]:
a3.shape

(4, 3)

In [45]:
a3[0]

array([1, 2, 3])

In [46]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [48]:
a2[1]

array([6. , 2.4, 4.5])

In [52]:
a3[:2,:2]

array([[1, 2],
       [4, 5]])

In [54]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]], dtype=int32)

In [55]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [56]:
# get the first 4 numbers of the inner most arrays 
a4[:,:,:,:1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]], dtype=int32)