In [1]:
import numpy as np

## DataTypes and Attributes


In [2]:
# Numpy main datatype is ndarray
al=np.array([1,2,3])

In [3]:
al

array([1, 2, 3])

In [5]:
type(al)

numpy.ndarray

In [10]:
a2=np.array([[1,2,3.3],[6,2.4,4.5]])

a3=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [12]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [17]:
a3.shape

(4, 3)

In [21]:
al

array([1, 2, 3])

In [20]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
al.ndim , a2.ndim , a3.ndim

(1, 2, 2)

In [23]:
al.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [24]:
al.size,a2.size,a3.size

(3, 6, 12)

In [25]:
type(al),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [28]:
# Create a datafram from numpy arrays

import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  6.0  2.4  4.5