In [1]:
import numpy as np

## DataTypes and Attributes


In [2]:
# Numpy main datatype is ndarray
al=np.array([1,2,3])

In [3]:
al

array([1, 2, 3])

In [4]:
type(al)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3.3],[6,2.4,4.5]])

a3=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [7]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [9]:
a3.shape

(4, 3)

In [10]:
al

array([1, 2, 3])

In [11]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
al.ndim , a2.ndim , a3.ndim

(1, 2, 2)

In [13]:
al.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
al.size,a2.size,a3.size

(3, 6, 12)

In [15]:
type(al),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [17]:
# Create a datafram from numpy arrays

import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  6.0  2.4  4.5

## Creating Arrays

In [18]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones=np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[8, 7, 1, 3, 3],
       [1, 9, 3, 0, 4],
       [3, 8, 3, 8, 3]], dtype=int32)

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.27177654, 0.56313399, 0.47842986],
       [0.7758942 , 0.70190854, 0.02758519],
       [0.5221621 , 0.55319045, 0.65413129],
       [0.91211831, 0.29278166, 0.76952174],
       [0.2316815 , 0.15881502, 0.4980655 ]])

In [30]:
random_array_2.size

15

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.31220637, 0.17140831, 0.35158462],
       [0.79326988, 0.79495282, 0.87323408],
       [0.49465618, 0.01016812, 0.02771047],
       [0.27280671, 0.31324696, 0.55671463],
       [0.33042135, 0.42900329, 0.26167301]])

In [33]:
#pseudo random numbers
np.random.seed(seed=99)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[1, 3, 9],
       [8, 9, 8],
       [2, 4, 5],
       [4, 1, 7],
       [3, 7, 1]], dtype=int32)

In [34]:
random_array_4.shape

(5, 3)

In [35]:
np.random.seed(7)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [36]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [37]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 7, 8, 9], dtype=int32)

In [38]:
al


array([1, 2, 3])

In [39]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [40]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
al[0]

np.int64(1)

In [42]:
a2.shape

(2, 3)

In [43]:
a2[0]

array([1. , 2. , 3.3])

In [44]:
a3.shape

(4, 3)

In [45]:
a3[0]

array([1, 2, 3])

In [46]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [48]:
a2[1]

array([6. , 2.4, 4.5])

In [49]:
a3[:2,:2]

array([[1, 2],
       [4, 5]])

In [50]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]], dtype=int32)

In [51]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [52]:
# get the first 4 numbers of the inner most arrays 
a4[:,:,:,:1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]], dtype=int32)

## Manipulating & Comparing Arrays 

## Arithmetic

In [54]:
al

array([1, 2, 3])

In [55]:
ones=np.ones(3)

In [56]:
ones

array([1., 1., 1.])

In [57]:
al+ones

array([2., 3., 4.])

In [58]:
al-ones

array([0., 1., 2.])

In [59]:
al*ones

array([1., 2., 3.])

In [62]:
al

array([1, 2, 3])

In [60]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [61]:
al*a2

array([[ 1. ,  4. ,  9.9],
       [ 6. ,  4.8, 13.5]])

In [64]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
#how can you reshape a2 to compatible with a3 ?
# search how to reshape any array
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [67]:
al/ones

array([1., 2., 3.])

In [68]:
a2/al

array([[1. , 1. , 1.1],
       [6. , 1.2, 1.5]])

In [69]:
#Floor div removes the decimals (rounds down)
a2//al

array([[1., 1., 1.],
       [6., 1., 1.]])

In [71]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [70]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [36.  ,  5.76, 20.25]])

In [72]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [36.  ,  5.76, 20.25]])

In [73]:
al+ones

array([2., 3., 4.])

In [74]:
np.add(al,ones)

array([2., 3., 4.])

In [75]:
al%2

array([1, 0, 1])

In [76]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 0.4, 0.5]])

In [77]:
np.exp(al)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [78]:
np.log(al)

array([0.        , 0.69314718, 1.09861229])