In [1]:
import numpy as np

## DataTypes and Attributes


In [2]:
# Numpy main datatype is ndarray
al=np.array([1,2,3])

In [3]:
al

array([1, 2, 3])

In [4]:
type(al)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3.3],[6,2.4,4.5]])

a3=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [7]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [9]:
a3.shape

(4, 3)

In [10]:
al

array([1, 2, 3])

In [11]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
al.ndim , a2.ndim , a3.ndim

(1, 2, 2)

In [13]:
al.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
al.size,a2.size,a3.size

(3, 6, 12)

In [15]:
type(al),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
a2

array([[1. , 2. , 3.3],
       [6. , 2.4, 4.5]])

In [17]:
# Create a datafram from numpy arrays

import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  6.0  2.4  4.5

## Creating Arrays

In [18]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [21]:
ones=np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[4, 6, 7, 0, 1],
       [6, 0, 9, 7, 1],
       [6, 7, 4, 8, 2]], dtype=int32)

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [32]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.69103346, 0.12789298, 0.32912642],
       [0.52714093, 0.13870384, 0.15546582],
       [0.83461806, 0.88025515, 0.24341014],
       [0.48844   , 0.76085887, 0.91571094],
       [0.64727777, 0.65731438, 0.38239208]])

In [33]:
random_array_2.size

15

In [34]:
random_array_2.shape

(5, 3)

In [35]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.89869952, 0.08914149, 0.98599613],
       [0.50422578, 0.50807028, 0.06551221],
       [0.48913205, 0.43523308, 0.46317063],
       [0.56420309, 0.19562615, 0.07075813],
       [0.21962416, 0.99240193, 0.41906604]])

In [ ]:
#pseudo random numbers
np.random.seed()